title: "My Blog"
description: "Rants, notes, and dev experiments"
url: "https://your-username.github.io"
baseurl: "" # set to "/repo-name" if not a user site
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
author:
  name: "djblackberry64"
  email: "not given"
